cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/services'

# Desktop Application
cask 'google-japanese-ime'
cask 'google-chrome'
cask 'google-photos-backup'
cask 'avira-antivirus'
cask 'alfred'
cask 'bettertouchtool'
cask 'contexts'
cask 'iterm2'
cask 'karabiner-elements'
cask 'forklift'
cask 'dash'
cask 'skim'
cask 'vlc'
cask 'slack'
cask 'the-unarchiver'
cask 'insomniax'
cask 'appcleaner'
cask 'imageoptim'
cask 'franz'
cask 'dropbox'
cask 'kindle'
cask 'xquartz'
cask 'parallels-desktop'
cask 'sketch'

# Appstore
mas '1Password', id: 443987910
mas 'Quiver', id: 866773894
mas 'Fantastical2', id: 975937182
mas 'LINE', id: 539883307
mas 'Memory Cleaner X', id: 518830108
mas 'PopClip', id: 445189367
mas 'まるごと英和検索 for 英辞郎', id: 919856506
mas 'Wunderlist', id: 410628904
mas 'Instant Translate', id: 1005088137


# Normal brew
brew 'wget'
